version: "3"

x-logging: 
  &default-logging
  driver: journald

services:
  web:
    image: nginx
    ports:
    - 80:80
    volumes:
    - ./nginx/conf.d/jenkins.conf:/etc/nginx/conf.d/jenkins.conf
    - ./nginx/conf.d/nexus.conf:/etc/nginx/conf.d/nexus.conf
    networks:
      stack:
        ipv4_address: 192.168.0.10
    logging: *default-logging
    depends_on:
    - jenkins
    - nexus

  jenkins:
    image: jenkins/jenkins
    environment:
    - JAVA_OPTS=
        -Djenkins.install.runSetupWizard=false
    volumes:
    - jenkins_data:/var/jenkins_home
    networks:
      stack:
        ipv4_address: 192.168.0.20
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 500M
    logging: *default-logging
          
  nexus:
    image: sonatype/nexus3
    volumes:
    - nexus_data:/nexus-data
    networks:
      stack:
        ipv4_address: 192.168.0.30
    deploy:
      resources:
        limits:
          cpus: '0.25'
    logging: *default-logging
          
volumes:
    jenkins_data:
    nexus_data:
    
networks:
  stack:
    name: custom_stack
    ipam:      
      config:
      - subnet: 192.168.0.0/24